version: 0.2

phases:
  # install: 
  #   commands:
  #     - apt-get install jq
  build:
    commands:
       - jq
       - aws codepipeline list-pipeline-executions  --pipeline-name test-environment-variables --max-items 1 | jq -r '.pipelineExecutionSummaries[0].sourceRevisions[0]' | jq '.CommitMessage'
       - CommitMessage2=$(aws codepipeline list-pipeline-executions  --pipeline-name test-environment-variables --max-items 1 | jq -r '.pipelineExecutionSummaries[0].sourceRevisions[0].revisionSummary' | jq '.CommitMessage') 
       - export CommitMessage2
      - echo Testing the env var now...
      - echo Github Version 1 again
      - echo $test
      - echo $CommitID
      - echo $RepositoryName
      - echo $CommitMessage2
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
# artifacts:
#   files:
#     - hello
